### ISSUE TITLE
LDA模型训练

### ISSUE THREAD

**Issue by countback** [dongrixinyu/chinese_keyphrase_extractor#2]
非常感谢代码，问一下LDA模型是用什么工具训练的，因为想做领域关键词的挖掘，需要针对领域训练一个新的LDA模型

**Comment by dongrixinyu** [comment]
lda 的工具很多，gensim，sklearn，familia 都可以的

**Comment by countback** [comment]
> lda 的工具很多，gensim，sklearn，familia 都可以的

我用gensim训练完了lda模型之后，得到topic_word_weight.json和word_topic_weight.json是不是还需要做额外的归一化操作，我发现我得到的文件值跟你的值有很大的差别，方便的话可以提供从lda_model到两个json文件的脚本吗？

**Comment by dongrixinyu** [comment]
需要归一化

**Comment by dongrixinyu** [comment]
> > lda 的工具很多，gensim，sklearn，familia 都可以的
> 
> 我用gensim训练完了lda模型之后，得到topic_word_weight.json和word_topic_weight.json是不是还需要做额外的归一化操作，我发现我得到的文件值跟你的值有很大的差别，方便的话可以提供从lda_model到两个json文件的脚本吗？

需要归一化
