### ISSUE TITLE
关于pos_combine_weights.json

### ISSUE THREAD

**Issue by lisuq** [dongrixinyu/chinese_keyphrase_extractor#6]
请问，pos_combine_weights.json的统计具体是怎么做的？统计所有词性频数，最后归一化？

**Comment by dongrixinyu** [comment]
人工标注的关键短语具有一定的词性分布，如多少偏正短语，多少动宾短语。而实际算法抽取出来的结果也有一个词性分布。这两个分布是不一致的，所以对短语的词性分布做了一个调整，调整的方法就是对两个分布做弥合。弥合方法就是 上述文件的权重。

**Comment by xinyinanxi** [comment]
您好！请问idf.txt，pos_combine_weights.json，topic_word_weight.json，word_topic_weight.json三个文件需要用自己的文本训练吗？如果是的话，如何训练呢？谢谢！

**Comment by dongrixinyu** [comment]
@xinyinanxi 都可以通过自定义的语料训练得到，其中 idf.txt 用 tfidf 算法统计得到。pos_combine 可以当做参数自由调节。后面两个主要参考 lda 模型以及我 readme 的两篇论文来计算。公式非常简单，是相对熵统计信息量。
