### ISSUE TITLE
会提取什么样的关键词？

### ISSUE THREAD

**Issue by ljw23** [dongrixinyu/chinese_keyphrase_extractor#7]
我按你的步骤试了一下，发现提取出的关键词完全不是我想要的，比如我输入的是一本金融教材的文本，但是返回给我的topk的词有很多“第五十”这样完全无意义的短语，不知这个工具对场景有什么要求？

**Comment by dongrixinyu** [comment]
第一，第五十这样的词，北大分词工具标记为了名词。这是分词器的问题，你可以替换别的你认为好用的。
第二，关键短语完全不是你想要的，你需要确认，你的需求到底是关键短语，还是“你认为关键的“短语。另外，语料影响很大，你需要根据你的语料单独制作一份权重文件，见readme
