### ISSUE TITLE
可以提供生成三个json文件的代码吗？

### ISSUE THREAD

**Issue by Tycoonman-ML** [dongrixinyu/chinese_keyphrase_extractor#8]
想使用专有领域的数据训练主题模型后提取关键短语，可是训练主题模型如何保存为topic_word_weight.json与word_topic_weight.json文件？

**Comment by dongrixinyu** [comment]
代码已经丢失了。不过比较简单，使用gensim训练 lda，然后把里面的参数保存下来，计算成需要的格式即可，公式论文里有。

**Comment by kinghmy** [comment]
> 。

pkuseg的模型，如何单独下载安装啊？ 它提供的教程 门槛太高了

**Comment by kinghmy** [comment]
> 代码已经丢失了。不过比较简单，使用gensim训练 lda，然后把里面的参数保存下来，计算成需要的格式即可，公式论文里有。

pkuseg的模型，如何单独下载安装啊？ 它提供的教程 门槛太高了
